#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#i_cumulative_merkle_rewards;
pub mod r#i_curator_registry;
pub mod r#i_fee_registry;
pub mod r#i_oz_eip712;
pub mod r#i_protocol_fees;
pub mod r#i_rewards;
pub mod r#i_vault_snapshot_rewards;
